### ISSUE TITLE
Player is never assigned color

### ISSUE THREAD

**Issue by johnellison** [sprky/sprky_chess#127] opened 2015-04-30 17:18 UTC
In adding pawn promotion I was using a bit of ruby to show the images of the pawn promotion pieces they could choose from. I used `<%= image_tag "#{current_player.color}-queen.svg" %>` and the image wasn't showing up because `current_player.color` returned `nil`. I looked around and nowhere in our application does the player get assigned color. It gets assigned pieces with colors according to their ID, not their color...

**Comment by washburnad** [comment] 2015-04-30 17:36
png isn't showing for me.  Can you describe?

**Comment by hsinkoff** [comment] 2015-04-30 17:46
I believe the issue is that when a player is invited by email and joins a game they aren't assigned to be the black player, but the person who invites them has previously been assigned as white player so we need to add code to ensure the invitee is assigned to be the black player.

**Comment by johnellison** [comment] 2015-04-30 17:47
This is just regarding the white_player. I don't believe it has anything to do with the invitations becaues I'm working on the pawn-promotion-enhanced branch. Also, I wrote tests to assert that the black_player_id is in fact the id of the player that joins via the invitation. At least I should have...

**Comment by hsinkoff** [comment] 2015-04-30 17:49
Sorry John,  
You did write those tests and you're correct about assigning player color with invited players.  I misunderstood our conversation in slack.

**Closed** 2015-05-01 16:35 UTC
Labels: bug
